Blog.PL/Controllers/MakaleController.cs
using Blog.BLL.Repository;
using Blog.DAL.Context;
using Blog.Entity.Entity;
using Blog.Entity.ViewModel;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blog.PL.Controllers
{
    [Authorize]
    public class MakaleController : BaseController
    {
        Repository<Article> repoM = new Repository<Article>(new BlogContext());
        Repository<Comment> repoC = new Repository<Comment>(new BlogContext());
        Repository<CommentAnswer> repoComAns = new Repository<CommentAnswer>(new BlogContext());
        Repository<Category> repoCat = new Repository<Category>(new BlogContext());
        public ActionResult Index()
        {
            return View(repoM.GetAll(null, m => m.OrderByDescending(x => x.CreatedDate)).Take(4));
        }
        //[Authorize(Roles = "Admin, Yazar")]
        [Authorize]
        public ActionResult Ekle()
        {
            return View();
        }
        public ActionResult YorumCevaplari(int id)
        {
            List<CommentAnswer> Answers = repoComAns.GetAll().Where(a => a.CommentId == id).ToList();
            return View("YorumCevaplari", Answers);
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult Ekle(MakaleAddViewModel model)
        {
            if (model.PictureUpload != null)
            {
                string filename = model.PictureUpload.FileName;
                string imagePath = Server.MapPath("/images/" + filename);
                model.PictureUpload.SaveAs(imagePath);
                Article yeni = new Article();
                yeni.Title = model.Title.Substring(0, 1).ToUpper() + model.Title.Substring(1);
                yeni.Summary = model.Summary.Substring(0, 1).ToUpper() + model.Summary.Substring(1);
                yeni.Content = model.Content;
                yeni.Picture = filename;
                yeni.CategoryId = model.CategoryId;
                yeni.UserId = HttpContext.User.Identity.GetUserId();
                if (repoM.Add(yeni))
                    return RedirectToAction("Index");
                return View(model);
            }
            return View();
        }
        public ActionResult MakaleDetay(int Id)
        {
            MakaleDetayViewModel mdvm = new MakaleDetayViewModel();
            mdvm.Makale = repoM.GetById(Id);
            mdvm.Yorum = new Comment();
            mdvm.Yorumlar = mdvm.Makale.Comments.ToList();
            return View(mdvm);
        }
        [HttpPost]
        public ActionResult MakaleDetay(MakaleDetayViewModel model)
        {
            MakaleDetayViewModel mdvm = new MakaleDetayViewModel();
            Comment yeniYorum = new Comment();
            yeniYorum.ArticleId = model.Makale.Id;
            if (!string.IsNullOrEmpty(model.Yorum.Content))
            {
                yeniYorum.Content = model.Yorum.Content;
            }
            else
            {
                mdvm.Makale = repoM.GetById(model.Makale.Id);
                mdvm.Yorum = new Comment();
                mdvm.Yorumlar = mdvm.Makale.Comments.ToList();
                return View(mdvm);
            }
            yeniYorum.UserId = HttpContext.User.Identity.GetUserId();
            if (repoC.Add(yeniYorum))
            {
                return Redirect("/Makale/MakaleDetay/" + model.Makale.Id);
            }
            mdvm.Makale = repoM.GetById(model.Makale.Id);
            mdvm.Yorum = new Comment();
            mdvm.Yorumlar = mdvm.Makale.Comments.ToList();
            return View(mdvm);
        }
        public ActionResult Kategoriler()
        {
            return View(repoCat.GetAll(c => c.IsDeleted == false));
        }
        public ActionResult KategoriEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult KategoriEkle(KategoriViewModel model)
        {
            Category yeniKategori = new Category();
            if (repoCat.GetAll(c => c.Name == model.Name).FirstOrDefault() != null)
            {
                yeniKategori = repoCat.GetAll(c => c.Name == model.Name).FirstOrDefault();
                
                if (yeniKategori.IsDeleted == false)
                {
                    ModelState.AddModelError("", "Bu kategori sistemde kayıtlı!");
                    return View(model);
                }
                else
                {
                    yeniKategori.CreatedDate = DateTime.Now;
                    if (string.IsNullOrEmpty(model.Description))
                    {
                        yeniKategori.Description = "Açıklama girilmemiş.";
                    }
                    else
                    {
                        yeniKategori.Description = model.Description.Substring(0, 1).ToUpper() + model.Description.Substring(1);
                    }
                    yeniKategori.Name = model.Name.Substring(0, 1).ToUpper() + model.Name.Substring(1);
                    yeniKategori.IsDeleted = false;
                    if (repoCat.Update(yeniKategori))
                    {
                        return Redirect("/Makale/Kategoriler/");
                    }
                    return View(model);
                }
            }
            yeniKategori.CreatedDate = DateTime.Now;
            if (string.IsNullOrEmpty(model.Description))
            {
                yeniKategori.Description = "Açıklama girilmemiş.";
            }
            else
            {
                yeniKategori.Description = model.Description.Substring(0, 1).ToUpper() + model.Description.Substring(1);
            }
            yeniKategori.Name = model.Name.Substring(0, 1).ToUpper() + model.Name.Substring(1);
            yeniKategori.IsDeleted = false;
            if (yeniKategori.Name.Length > 50)
            {
                ModelState.AddModelError("", "Kategori ismi 50 karakterden az olmalı!");
                return View(model);
            }
            if (repoCat.Add(yeniKategori))
            {
                return Redirect("/Makale/Kategoriler/");
            }

            return View(model);
        }
        public ActionResult KategoriDuzenle(int id)
        {
            KategoriViewModel model = new KategoriViewModel();
            Category kategori = repoCat.GetById(id);
            model.Description = kategori.Description.Substring(0, 1).ToUpper() + kategori.Description.Substring(1); ;
            model.Name = kategori.Name.Substring(0, 1).ToUpper() + kategori.Name.Substring(1); ;
            model.Id = kategori.Id;
            return View(model);
        }
        [HttpPost]
        public ActionResult KategoriDuzenle(KategoriViewModel model)
        {
            Category yeniKategori = repoCat.GetAll(c => c.Id == model.Id).FirstOrDefault();
            if (yeniKategori == null)
            {
                ModelState.AddModelError("", "Bu kategori sistemde bulunamadı!");
                return Redirect("/Makale/Kategoriler/");
            }
            yeniKategori.CreatedDate = DateTime.Now;
            if (string.IsNullOrEmpty(model.Description))
            {
                yeniKategori.Description = "Açıklama girilmemiş.";
            }
            else
            {
                yeniKategori.Description = model.Description.Substring(0, 1).ToUpper() + model.Description.Substring(1); ;
            }
            yeniKategori.Name = model.Name.Substring(0, 1).ToUpper() + model.Name.Substring(1); ;
            yeniKategori.IsDeleted = false;
            if (repoCat.Update(yeniKategori))
            {
                return Redirect("/Makale/Kategoriler/");
            }

            return View(model);
        }
        [HttpPost]
        public JsonResult KategoriSil(int id)
        {
            Category kategori = repoCat.GetById(id);
            kategori.IsDeleted = true;
            if (repoM.GetAll().Where(x => x.CategoryId == id).ToList().Count != 0)
            {
                return Json("NotDeleted", JsonRequestBehavior.AllowGet);
            }
            repoCat.Delete(kategori);
            return Json("Deleted", JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult CommentAnswer(int id, string comment)
        {
            Comment yorum = repoC.GetById(id);
            CommentAnswer newAnswer = new CommentAnswer();
            newAnswer.CommentId = yorum.Id;
            newAnswer.UserId = HttpContext.User.Identity.GetUserId();
            newAnswer.Content = comment;
            if (repoComAns.Add(newAnswer))
            {
                return Json("True", JsonRequestBehavior.AllowGet);
            }
            return Json("False", JsonRequestBehavior.AllowGet);
        }
    }
}

Blog.PL/Views/Makale/Ekle.cshtml
@model Blog.Entity.ViewModel.MakaleAddViewModel

@{
    ViewBag.Title = "Makale Ekle";
}
<script src="~/ckeditor/ckeditor.js"></script>
@using (Html.BeginForm("Ekle", "Makale", FormMethod.Post, new {encType="multipart/form-data" }))
{
<div class="form-horizontal">
    <h4>Yeni Makale</h4>
    <hr />
    <div class="form-group">
        @Html.Label("Kategori", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("CategoryId", new SelectList(ViewBag.Kategoriler, "Id", "Name"), new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Makale Özeti", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Summary, 5, 83, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Makale İçeriği", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Content, new { htmlAttributes = new { @class = "form-control ckeditor" } })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Resim Yükle", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.PictureUpload, new { type="file", name="PictureUpload", @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Kaydet" class="btn btn-default" />
        </div>
    </div>
</div>
}

<script>
    CKEDITOR.replace("Content", {
        uiColor: '#fc7f7f'
    });
</script>

Blog.PL/Views/Makale/Index.cshtml
@model IEnumerable<Blog.Entity.Entity.Article>
@{
    ViewBag.Title = "MVC Blog Projesi";
}
@if (Model.Count() == 0)
{
    <div class="masonry-grid-item">
        <p class="alert alert-info text-primary">Bu kategoride kayıtlı makale bulunmamaktadır.</p>
    </div>
}
else
{
    foreach (var item in Model)
    {
        <div class="masonry-grid-item col-md-6">
            <!-- blogpost start -->
            <article class="clearfix blogpost">
                <div class="overlay-container">
                    <img src="/images/@item.Picture" style="height:250px;" alt="">
                    <div class="overlay">
                        <div class="overlay-links">
                            <a href="/Makale/MakaleDetay/@item.Id"><i class="fa fa-link"></i></a>
                            <a href="/images/@item.Picture" class="popup-img-single" title='@item.Title'><i class="fa fa-search-plus"></i></a>
                        </div>
                    </div>
                </div>
                <div class="blogpost-body">
                    <div class="post-info">
                        <span class="day">@item.CreatedDate.Day</span>
                        <span class="month">
                            @item.CreatedDate.ToString("MMMM") @item.CreatedDate.Year
                            @*@string.Format("{0:y}", item.CreatedDate)*@
                            @*@item.CreatedDate. @item.CreatedDate.Year*@
                        </span>
                    </div>
                    <div class="blogpost-content" style="height:200px;">
                        <header>
                            <h2 class="title"><a href="blog-post.html">@item.Title</a></h2>
                            <div class="submitted"><i class="fa fa-user pr-5"></i> by <a href="#">@(item.User.Name + " " + item.User.Surname)</a></div>
                        </header>
                        @if (item.Summary.Length < 100)
                        {
                            <p class="wordwrap">@Html.Raw(item.Summary)</p>
                        }
                        else
                        {
                            <p class="wordwrap">@Html.Raw(item.Summary.Substring(0, 100))...</p>
                        }
                    </div>
                </div>
                <footer class="clearfix">
                    <ul class="links pull-left">
                        <li><i class="fa fa-comment-o pr-5"></i> <a href="#">@item.Comments.Count yorum</a> |</li>
                        <li><i class="fa fa-tags pr-5"></i> <a href="#">etiket @item.Tags.Count</a></li>
                    </ul>
                    <a class="pull-right link" href="/Makale/MakaleDetay/@item.Id"><span>Makale detayı</span></a>
                </footer>
            </article>
            <!-- blogpost end -->
        </div>
    }
}

Blog.PL/Views/Makale/KategoriDuzenle.cshtml
@model Blog.Entity.ViewModel.KategoriViewModel

@{
    ViewBag.Title = "Kategori Düzenle";
    Layout = "~/Views/Shared/_LayoutBlog.cshtml";
}

<h2>Kategori Düzenle</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Kategori</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2 col-md-offset-1" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2 col-md-offset-1" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-3 col-md-4">
                <input type="submit" value="Kaydet" class="btn btn-default" />
            </div>
        </div>
    </div>
}
    <div>
        @Html.ActionLink("Vazgeç", "Kategoriler", "Makale")
    </div>

Blog.PL/Views/Makale/KategoriEkle.cshtml
@model Blog.Entity.ViewModel.KategoriViewModel

@{
    ViewBag.Title = "Kategori Ekle";
    Layout = "~/Views/Shared/_LayoutBlog.cshtml";
}

<h2>Kategori Ekle</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Kategori</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2 col-md-offset-1" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2 col-md-offset-1" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-3 col-md-4">
                <input type="submit" value="Kaydet" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Vazgeç", "Kategoriler","Makale")
</div>

Blog.PL/Views/Makale/Kategoriler.cshtml
@model IEnumerable<Blog.Entity.Entity.Category>

@{
    ViewBag.Title = "Kategoriler";
    Layout = "~/Views/Shared/_LayoutBlog.cshtml";
}

<h2>Kategoriler</h2>

<p>
    @Html.ActionLink("Kategori Ekle", "KategoriEkle", "Makale")
</p>
<table class="table">
    <tr>
        <th>
            <label>Kategori Adı</label>
        </th>
        <th>
            <label>Açıklama</label>
        </th>
        <th>
            <label>Oluşturulma Tarihi</label>
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td class="wordwrap">
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td class="wordwrap">
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td class="wordwrap">
                @Html.DisplayFor(modelItem => item.CreatedDate)
            </td>
            <td>
                <a href="/Makale/KategoriDuzenle/@item.Id">Düzenle |</a>
                <a class="btnCatDelete" href="#" data-CatId="@item.Id"> Sil</a>
            </td>
        </tr>
    }

</table>
<script type="text/javascript">
    $(document).ready(function () {
        $(".btnCatDelete").click(function () {
            var CatID = $(this).data("catid");
            var r = confirm("Silmek istiyor musunuz!");
            if (r == true) {               
                $.ajax({
                    url: '/Makale/KategoriSil/' + CatID,
                    type: 'POST',
                    dataType: 'json',
                    success: function (data) {
                        if (data === "Deleted") {
                            alert("Kategori silinidi.");
                        }
                        else if (data === "NotDeleted") {
                            alert("Bu kategoride makaleler var! Makale bulunan kategoriler silinemez!");
                        }
                        window.location = "/Makale/Kategoriler/";
                    }
                });
            }
        });
    });
</script>

Blog.PL/Views/Makale/MakaleDetay.cshtml
@model Blog.Entity.ViewModel.MakaleDetayViewModel
@{
    ViewBag.Title = "Makale Detay";
}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
<div class="container-fluid">
    <div class="row">
        <!-- main start -->
        <!-- ================ -->
        <div class="main col-md-offset-1 col-md-9">
            <!-- page-title start -->
            <!-- ================ -->
            <h1 class="page-title wordwrap">@Model.Makale.Title</h1>
            <!-- page-title end -->
            <!-- blogpost start -->
            <article class="clearfix blogpost full">
                <div class="blogpost-body">
                    <div class="side">
                        <div class="post-info">
                            <span class="day">@Model.Makale.CreatedDate.Day</span>
                            <span class="month">@Model.Makale.CreatedDate.ToString("MMMM") @Model.Makale.CreatedDate.Year</span>
                        </div>
                    </div>
                    <div class="blogpost-content">
                        <header>
                            <div class="submitted"><i class="fa fa-user pr-5"></i> by <a href="#">@(Model.Makale.User.Name + " " + Model.Makale.User.Surname)</a></div>
                        </header>
                        <div class="owl-carousel content-slider-with-controls">
                            <div class="overlay-container">
                                <img src="/images/@Model.Makale.Picture" alt="@Model.Makale.Title">
                                @*<a href="images/blog-1.jpg" class="popup-img overlay" title="image title"><i class="fa fa-search-plus"></i></a>*@
                            </div>
                            <div class="overlay-container">
                                <img src="/images/@Model.Makale.Picture" alt="@Model.Makale.Title">
                                @*<a href="images/blog-2.jpg" class="popup-img overlay" title="image title"><i class="fa fa-search-plus"></i></a>*@
                            </div>
                            <div class="overlay-container">
                                <img src="/images/@Model.Makale.Picture" alt="@Model.Makale.Title">
                                @*<a href="images/blog-3.jpg" class="popup-img overlay" title="image title"><i class="fa fa-search-plus"></i></a>*@
                            </div>
                        </div>
                        <p class="wordwrap">
                            @Html.Raw(Model.Makale.Content)
                        </p>
                    </div>
                </div>
                <footer class="clearfix">
                    <ul class="links pull-left">
                        <li><i class="fa fa-comment-o pr-5"></i> <a href="#">@Model.Makale.Comments.Count yorum</a> |</li>
                        <li><i class="fa fa-tags pr-5"></i> <a href="#">etiket @Model.Makale.Tags.Count</a></li>
                    </ul>
                </footer>
            </article>
            <!-- blogpost end -->
            <!-- comments start -->
            <div class="comments">
                @if (Model.Makale.Comments.Count == 0)
                {
                    <h2 class="title">Henüz yorum eklenmemiştir.</h2>
                }
                else
                {
                    <h2 class="title">@Model.Makale.Comments.Count yorum eklenmiştir.</h2>
                    foreach (var yorum in Model.Yorumlar)
                    {
                        <!-- comment start -->
                        <div class="comment clearfix">
                            <div class="comment-avatar">
                                <img src="images/avatar.jpg" alt="avatar">
                            </div>
                            <div class="comment-content">
                                <h3>Yorum</h3>
                                <div class="comment-meta">By <a class="wordwrap" href="#">@(yorum.User.Name + " " + yorum.User.Surname)</a> | Today, 12:31</div>
                                <div class="comment-body clearfix">
                                    <p class="wordwrap">@yorum.Content</p>
                                    <button type="button" class="btn btn-gray more pull-right ComAnswIdSelect" data-toggle="modal" data-target="#CommentAnswerModal" data-comid="@yorum.Id">
                                        Cevapla
                                    </button>
                                    @if (yorum.CommentAnswers.Count != 0)
                                    {
                                        <button type="button" class="btn btn-gray more pull-left btnAnswers" data-comid="@yorum.Id">
                                            Yanıtları Gör<span class="badge badge-light">@yorum.CommentAnswers.Count.ToString()</span>
                                        </button>}
                                </div>
                            </div>
                        </div>
                    }
                    <!-- comment end -->
                }
            </div>
            <!-- comments form start -->
            @using (Html.BeginForm("MakaleDetay", "Makale", FormMethod.Post))
            {
                <div class="comments-form">
                    <h2 class="title">Yorum Ekle</h2>
                    <div class="form-horizontal">
                        @Html.HiddenFor(model => model.Makale.Id)
                        <div class="form-group">
                            @Html.Label("Mesaj", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextAreaFor(model => model.Yorum.Content, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Kaydet" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                </div>
            }
            <!-- comments form end -->
            <!-- Modal -->
            <div class="modal fade" id="CommentAnswerModal" tabindex="-1" role="dialog" aria-labelledby="CommentAnswerModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <div class="row">
                                <h5 class="modal-title col-lg-9" id="CommentAnswerModalLabel">Cevabınızı Yazınız</h5>
                                <button type="button" class="close col-lg-1 btnYorumCevapIptal" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        </div>
                        <div class="modal-body">
                            <textarea class="form-control" type="text" id="txtComment" maxlength="200" rows="4"></textarea>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary btnYorumCevapIptal" data-dismiss="modal">İptal</button>
                            <a href="#" class="btn btn-primary btnYorumCevap">Gönder</a>
                        </div>
                    </div>
                </div>
            </div>
            <!--End Modal -->           
        </div>
        <!-- main end -->
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        var url = window.location.pathname;
        console.log(url);
        var ComID = 0;
        $(".btnAnswers").click(function () {
            ComID = $(this).data("comid");
            window.location ='/Makale/YorumCevaplari/' + ComID;
        });
        $(".ComAnswIdSelect").click(function () {
            ComID = $(this).data("comid");
        });
        $(".btnYorumCevap").click(function () {
            var Comm = $("#txtComment").val();
            if (ComID !== 0) {
                if (Comm !== "") {
                    $.ajax({
                        url: '/Makale/CommentAnswer/' + ComID,
                        data: { comment: Comm },
                        type: 'POST',
                        dataType: 'json',
                        success: function (data) {
                            if (data === "True") {
                                window.location = url;
                            }
                            else {
                                alert("Cevap eklenemedi!")
                            }
                        }
                    });
                } else {
                    alert("Cevap yazmalısınız!");
                }
            }
        });
        $(".btnYorumCevapIptal").click(function () {
            ComID = 0;
            $("#txtComment").val("");
        });
    });
</script>

Blog.PL/Views/Makale/YorumCevaplari.cshtml
@model IEnumerable<Blog.Entity.Entity.CommentAnswer>

@{
    ViewBag.Title = "Yorum Cevapları";
    Layout = "~/Views/Shared/_LayoutBlog.cshtml";
}

<h2>Yorum Cevapları</h2>

<table class="table">
    <tr>
        <th>
            <label>Kullanıcı</label>
        </th>
        <th>
            <label>Yorum</label>
        </th>
        <th>
            <label>Oluşturulma Tarihi</label>
        </th>
        <th></th>
    </tr>
    <tr>
        <td class="wordwrap">
            <label>@Model.ToList().FirstOrDefault().Comment.User.UserName</label>
        </td>
        <td class="wordwrap">
            <label>@Model.ToList().FirstOrDefault().Comment.Content</label>
        </td>
        <td class="wordwrap">
            <label>@Model.ToList().FirstOrDefault().Comment.CreatedDate</label>
        </td>
    </tr>
    <tr>
       <td>
           -
       </td>
    </tr>
    <tr>
        <th>
            <label>Kullanıcı</label>
        </th>
        <th>
            <label>Yanıt</label>
        </th>
        <th>
            <label>Oluşturulma Tarihi</label>
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td class="wordwrap">
                @Html.DisplayFor(modelItem => item.User.UserName)
            </td>
            <td class="wordwrap">
                @Html.DisplayFor(modelItem => item.Content)
            </td>
            <td class="wordwrap">
                @Html.DisplayFor(modelItem => item.CreatedDate)
            </td>
        </tr>
    }

</table>